[project]
name = "recomendation-system"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "lightgbm>=4.6.0",
    "pandas>=2.3.2",
    "psycopg2>=2.9.10",
    "pydantic>=2.11.9",
    "scikit-learn>=1.7.2",
]
